name: Deploy Pages

on:
  push:
    paths-ignore:
      - "images/**"
      - "LICENSE"
      - "README.md"
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: true


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.83.0"
    steps:
      - name: 安装 pnpm...
        uses: pnpm/action-setup@v2
        with:
          version: 7.5.0
      - name: 安装 nodejs...
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 获取 master 分支代码
        uses: actions/checkout@v3
        with:
          ref: master

      - name: 安装 项目依赖 ...
        run: pnpm i

      - name: 打包 项目
        run: pnpm build

      - name: 部署 pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAGES_TOKEN }}
          publish_dir: ./dist

